In [1]:
# Importing the required packages 
import numpy as np 
import pandas as pd 
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

In [41]:
# Function importing Dataset 
def importdata(): 
    balance_data = pd.read_csv( 
'https://archive.ics.uci.edu/ml/machine-learning-'+
'databases/balance-scale/balance-scale.data', 
    sep= ',', header = None) 
      
    # Printing the dataset shape 
    print ("Dataset Length: ", len(balance_data)) 
    print ("Dataset Shape: ", balance_data.shape) 
      
    # Printing the dataset obseravtions 
    print ("Dataset: ", '\n', balance_data.head()) 
    return balance_data 

In [3]:
importdata()

Dataset Length:  625
Dataset Shape:  (625, 5)
Dataset:     0  1  2  3  4
0  B  1  1  1  1
1  R  1  1  1  2
2  R  1  1  1  3
3  R  1  1  1  4
4  R  1  1  1  5


0  1  2  3  4
0    B  1  1  1  1
1    R  1  1  1  2
2    R  1  1  1  3
3    R  1  1  1  4
4    R  1  1  1  5
5    R  1  1  2  1
6    R  1  1  2  2
7    R  1  1  2  3
8    R  1  1  2  4
9    R  1  1  2  5
10   R  1  1  3  1
11   R  1  1  3  2
12   R  1  1  3  3
13   R  1  1  3  4
14   R  1  1  3  5
15   R  1  1  4  1
16   R  1  1  4  2
17   R  1  1  4  3
18   R  1  1  4  4
19   R  1  1  4  5
20   R  1  1  5  1
21   R  1  1  5  2
22   R  1  1  5  3
23   R  1  1  5  4
24   R  1  1  5  5
25   L  1  2  1  1
26   B  1  2  1  2
27   R  1  2  1  3
28   R  1  2  1  4
29   R  1  2  1  5
..  .. .. .. .. ..
595  L  5  4  5  1
596  L  5  4  5  2
597  L  5  4  5  3
598  B  5  4  5  4
599  R  5  4  5  5
600  L  5  5  1  1
601  L  5  5  1  2
602  L  5  5  1  3
603  L  5  5  1  4
604  L  5  5  1  5
605  L  5  5  2  1
606  L  5  5  2  2
607  L  5  5  2  3
608  L  5  5  2  4
609  L  5  5  2  5
610  L  5  5  3  1
611  L  5  5  3  2
612  L  5  5  3  3
613  L  5  5  3  4
614  L  5  5  3  5
615  L  5  5  4  1
616  L  5  5  4  2
617  L  5  5  4  3
618  L  5  5  4  4
619  L  5  5  4  5
620  L  5  5  5  1
621  L  5  5  5  2
622  L  5  5  5  3
623  L  5  5  5  4
624  B  5  5  5  5

[625 rows x 5 columns]

In [27]:
# Function to split the dataset 
def splitdataset(balance_data): 
  
    # Seperating the target variable 
    X = balance_data.values[:, 1:5] 
    Y = balance_data.values[:, 0] 
  
    # Spliting the dataset into train and test 
    X_train, X_test, y_train, y_test = train_test_split(  
    X, Y, test_size = 0.2, random_state = 10) 
      
    return X, Y, X_train, X_test, y_train, y_test

In [28]:
# Function to perform training with giniIndex. 
def train_using_gini(X_train, X_test, y_train): 
  
    # Creating the classifier object 
    clf_gini = DecisionTreeClassifier(criterion = "gini", 
            random_state = 100, max_depth=3, min_samples_leaf=5) 
    # Performing training 
    clf_gini.fit(X_train, y_train) 
    return clf_gini 
  

In [29]:
# Function to perform training with entropy. 
def train_using_entropy(X_train, X_test, y_train): 
  
    # Decision tree with entropy 
    clf_entropy = DecisionTreeClassifier( 
            criterion = "entropy", random_state = 100, 
            max_depth = 3, min_samples_leaf = 5) 
  
    # Performing training 
    clf_entropy.fit(X_train, y_train) 
    return clf_entropy 

In [30]:
# Function to make predictions 
def prediction(X_test, clf_object): 
  
    # Predicton on test with giniIndex 
    y_pred = clf_object.predict(X_test) 
    #print("Predicted values:") 
    #print(y_pred) 
    return y_pred 

In [34]:
# Function to calculate accuracy 
def cal_accuracy(y_test, y_pred): 
      
    print("Confusion Matrix: ",  '\n',
        confusion_matrix(y_test, y_pred)) 
      
    print ("Accuracy : ", 
    accuracy_score(y_test,y_pred)*100) 
      
    print("Report : ", 
    classification_report(y_test, y_pred)) 
  

In [35]:
# Driver code 
def main(): 
      
    # Building Phase 
    data = importdata() 
    X, Y, X_train, X_test, y_train, y_test = splitdataset(data) 
    clf_gini = train_using_gini(X_train, X_test, y_train) 
    clf_entropy = train_using_entropy(X_train, X_test, y_train) 
      
    # Operational Phase 
    print("Results Using Gini Index:") 
      
    # Prediction using gini 
    y_pred_gini = prediction(X_test, clf_gini) 
    cal_accuracy(y_test, y_pred_gini) 
      
    print("Results Using Entropy:") 
    # Prediction using entropy 
    y_pred_entropy = prediction(X_test, clf_entropy) 
    cal_accuracy(y_test, y_pred_entropy)

In [42]:
# Calling main function 
if __name__=="__main__": 
    main() 

Dataset Length:  625
Dataset Shape:  (625, 5)
Dataset:  
    0  1  2  3  4
0  B  1  1  1  1
1  R  1  1  1  2
2  R  1  1  1  3
3  R  1  1  1  4
4  R  1  1  1  5
Results Using Gini Index:
Confusion Matrix:  
 [[ 0  1  5]
 [ 0 44 16]
 [ 0  7 52]]
Accuracy :  76.8
Report :                precision    recall  f1-score   support

           B       0.00      0.00      0.00         6
           L       0.85      0.73      0.79        60
           R       0.71      0.88      0.79        59

   micro avg       0.77      0.77      0.77       125
   macro avg       0.52      0.54      0.52       125
weighted avg       0.74      0.77      0.75       125

Results Using Entropy:
Confusion Matrix:  
 [[ 0  1  5]
 [ 0 46 14]
 [ 0 11 48]]
Accuracy :  75.2
Report :                precision    recall  f1-score   support

           B       0.00      0.00      0.00         6
           L       0.79      0.77      0.78        60
           R       0.72      0.81      0.76        59

   micro avg       0.7

//anaconda3/envs/nf/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
//anaconda3/envs/nf/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
